name: tool_mobile
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  tool_base:
    #    path: ../tool_base
    git: https://github.com/mmcc007/tool_base.git

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: 4.1.0